POST http://localhost:3002/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikt4bGEiLCJpZCI6IjYxYWI1ZTgxNmJlZTFmYjg0ODY4ODVlNCIsImlhdCI6MTYzODYyMDgyMH0.42mGCvbxN7G44P29RS_ZOaBaOFLSo6JOKaxtv_Ct4tg

{
  "title": "Dont be stypid, stupid Wyling",
  "author": "Wyling May",
  "url": "https://www.codingame.com/playgrounds/7998/es6-tutorials-spread-operator-with-fun",
  "likes": 7,
  "userId": "61ab5e816bee1fb8486885e4"
}
